const runButtonTypes = {
  RUN_GAME: "RUN_GAME",
  STOP_GAME: "STOP_GAME",
  CLEAR_GAME: "CLEAR_GAME",
  DRAG_TARGET: "DRAG_TARGET",
  ADD_OBSTACLE: "ADD_OBSTACLE",
  TOGGLE_ADD_OBSTACLE: "TOGGLE_ADD_OBSTACLE",
  CLEAR_OBSTACLES: "CLEAR_OBSTACLES",
  SELECT_SEARCH_ALGORITHM: "SELECT_SEARCH_ALGORITHM"
};

export default runButtonTypes;
