const searchTypes = {
  RUN_SEARCH: "RUN_SEARCH",
  STOP_SEARCH: "STOP_SEARCH",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  DRAG_TARGET: "DRAG_TARGET",
  ADD_OBSTACLE: "ADD_OBSTACLE",
  TOGGLE_ADD_OBSTACLE: "TOGGLE_ADD_OBSTACLE",
  CLEAR_OBSTACLES: "CLEAR_OBSTACLES",
  SELECT_SEARCH_ALGORITHM: "SELECT_SEARCH_ALGORITHM",
  SELECT_MAZE_ALGORITHM: "SELECT_MAZE_ALGORITHM",
  GENERATE_MAZE: "GENERATE_MAZE"
};

export default searchTypes;
